server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback: sve nepostojece putanje -> index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # WASM fajlovi moraju imati tacan MIME type
    location ~ \.wasm$ {
        add_header Content-Type application/wasm;
    }
}